#???? ??
spring:
  profiles:
    active: dev #??

#dev
---
spring:
  #db ??
  datasource:
    url: jdbc:oracle:thin:@blueblue_high?TNS_ADMIN=D:\\oracleDB\\Wallet_blueblue
    driver-class-name: oracle.jdbc.OracleDriver
    username: DEVUSER
    password: BlueBlue129323
  #??? ????
  security:
    user: #??? ???? ?? ??? ????
      name: dev
      password: 1234
  config:
    activate:
      on-profile: dev
  thymeleaf:
    prefix: classpath:templates/ #view prefix
    suffix: .html
    cache: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true #jpa sql ???? format
  devtools: #????? - ??? ?? html? resource ?? ??
    restart:
      enabled: false

#????
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#??
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
