#############################################################################################################################################################

#프로파일 설정
spring:
  profiles:
    active: dev1 #프로파일 선택

#############################################################################################################################################################

---
spring:
  config:
    activate:
      on-profile: dev1 #동제쿤
  #db 세팅
  datasource:
    url: jdbc:oracle:thin:@portfoliodb_high?TNS_ADMIN=C:\\portfolio\\oracle-cloud\\database\\Wallet_PortfolioDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: PortfolioDev1
    password: Portfolio1_777
  #스프링 시큐리티
  security:
    user: #스프링 시큐리티 기본 로그인 계정정보
      name: dev
      password: 1234
  #frontTemplateEngine
  thymeleaf:
    prefix: classpath:/templates/ #view prefix
    suffix: .html
    cache: false
  #DB ORM
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true #jpa sql 예쁘게 format
  devtools: # 재기동 없이 resources 적용
    restart:
      enabled: false
#로깅설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#서버
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/**.xml   #xml파일 경로설정
#############################################################################################################################################################

#############################################################################################################################################################
---
spring:
  config:
    activate:
      on-profile: dev2 #상민쿤
  #db 세팅
  datasource:
    url: jdbc:oracle:thin:@portfoliodb_high?TNS_ADMIN=/LSM/db/Wallet_PortfolioDB/
    driver-class-name: oracle.jdbc.OracleDriver
    username: PortfolioDev1
    password: Portfolio1_777
  #스프링 시큐리티
  security:
    user: #스프링 시큐리티 기본 로그인 계정정보
      name: dev
      password: 1234
  #frontTemplateEngine
  thymeleaf:
    prefix: classpath:/templates/ #view prefix
    suffix: .html
    cache: false
  #DB ORM
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true #jpa sql 예쁘게 format
  devtools: # 재기동 없이 resources 적용
    restart:
      enabled: false
#로깅설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#서버
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/**.xml   #xml파일 경로설정
#############################################################################################################################################################

#############################################################################################################################################################
---
spring:
  config:
    activate:
      on-profile: prod #운영서버쿤
  #db 세팅
  datasource:
    url: jdbc:oracle:thin:@portfoliodb_high?TNS_ADMIN=/home/portfolio/oracle-cloud/database/Wallet_PortfolioDB/
    driver-class-name: oracle.jdbc.OracleDriver
    username: PortfolioDev1
    password: Portfolio1_777
  #스프링 시큐리티
  security:
    user: #스프링 시큐리티 기본 로그인 계정정보
      name: dev
      password: 1234
  #frontTemplateEngine
  thymeleaf:
    prefix: classpath:/templates/ #view prefix
    suffix: .html
    cache: false
  #DB ORM
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true #jpa sql 예쁘게 format
  devtools: # 재기동 없이 resources 적용
    restart:
      enabled: false

#로깅설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#서버
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/**.xml   #xml파일 경로설정
#############################################################################################################################################################
