#프로파일 설정
spring:
  profiles:
    active: dev #세팅

#dev
---
spring:
  config:
    activate:
      on-profile: dev
  #db 세팅
  datasource:
    url: jdbc:oracle:thin:@blueblue_high?TNS_ADMIN=/portfolio/oracle-cloud/database/Wallet_blueblue
    driver-class-name: oracle.jdbc.OracleDriver
    username: DEVUSER
    password: BlueBlue129323
  #스프링 시큐리티
  security:
    user: #스프링 시큐리티 기본 로그인 계정정보
      name: dev
      password: 1234
  #frontTemplateEngine
  thymeleaf:
    prefix: classpath:templates/ #view prefix
    suffix: .html
    cache: false
  #DB ORM
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true #jpa sql 예쁘게 format
  devtools: # 재기동 없이 resources 적용
    restart:
      enabled: false

#로깅설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#서버
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
